services:
  db:
    container_name: tailkeep-postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: tailkeep
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
  redis:
    image: redis
    container_name: tailkeep-redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/data
    entrypoint: redis-server --appendonly yes
    restart: unless-stopped

networks:
  tailkeep:
    name: tailkeep
    driver: bridge
