version: '3'

services:
  db:
    container_name: postgres
    image: postgres:alpine
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: next_tasks
    ports:
      - 5432:5432
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/data
    entrypoint: redis-server --appendonly yes

networks:
  tailkeep:
    name: tailkeep
    driver: bridge
