version: '3'

services:
  tailkeep-server-dev:
    container_name: tailkeep-server-dev
    # Note that the path of the Dockerfile and context is relative to the *primary*
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    build:
      context: .
      dockerfile: ../.devcontainer/Dockerfile

    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ./config.txt:/etc/yt-dlp/config.txt:cached
      - ../:/workspace:cached
      - tailkeep-node:/workspace/node_modules/
      - tailkeep-next:/workspace/.next/

    depends_on:
      - db

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  tailkeep-node:
    driver: local
  tailkeep-next:
    driver: local
