http:
  #region routers
  routers:
    tailkeep:
      entryPoints:
        - 'https'
      rule: 'Host(`demo.tailkeep.org`)'
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: tailkeep
    pihole:

  #endregion
  #region services
  services:
    tailkeep:
      loadBalancer:
        servers:
          - url: 'http://10.0.0.23:3000'
        passHostHeader: true
  #endregion
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipAllowList:
        sourceRange:
          - '10.0.0.0/8'
          - '192.168.0.0/16'
          - '172.16.0.0/12'

    secured:
      chain:
        middlewares:
          - default-whitelist
          - default-headers
